market/apps/cart/urls.py
from django.conf.urls import url

from cart.views import AddCartView

urlpatterns = [
    url(r'^add/$',AddCartView.as_view(),name="添加购物车"),
]

market/apps/goods/urls.py
from django.conf.urls import url

from goods.models import Category
from goods.views import DetailView, ListView, CategoryView,IndexView

urlpatterns = [
    url(r'^detail/(?P<id>\d+)/$',DetailView.as_view(),name='详情'),
    url(r'^cate/(?P<cate_id>\d*)_{1}(?P<order>\d?)\.html$', CategoryView.as_view(), name='分类列表'),
    url(r'^list/$',ListView.as_view(),name='店家列表'),
    url(r'^$',IndexView.as_view(),name='主页'),



]

market/apps/user/urls.py
from django.conf.urls import url

from user.views import RegisterView, LoginView, MemberView, ForgetView, SendMsm,InfoView

urlpatterns = [
    url(r'^register/', RegisterView.as_view(),name='注册'),
    url(r'^login/',LoginView.as_view(),name='登录'),
    url(r'^member/', MemberView.as_view(),name='个人中心'),
    # url(r'^changepwd/', ChangePasswordView.as_view(),name='修改密码'),
    url(r'^forget/', ForgetView.as_view(),name='忘记密码'),
    url(r'^sendMsg/',SendMsm.as_view(),name='发送短信验证码'),
    url(r'^info/',InfoView.as_view(),name='个人资料'),
]

market/market/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from user.views import RegisterView

urlpatterns = [
    #添加第三方插件
    # 上传部件自动调用的上传地址
    url(r'^ckeditor/', include("ckeditor_uploader.urls")),
    # 全文搜索框架
    url(r'^search/', include('haystack.urls', namespace='search')),

    #添加子路由
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('user.urls',namespace='user')),
    url(r'^goods/', include('goods.urls',namespace='goods')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
]

market/apps/cart/models.py
from django.db import models

# Create your models here.

market/apps/cart/views.py
from django.shortcuts import render

# Create your views here.

from django.http import HttpResponse, JsonResponse
from django.shortcuts import render

from cart.hepler import json_msg, get_cart_count
from db.base_view import VerifyLoginView
from goods.models import Goods_Sku
from django_redis import get_redis_connection


class AddCartView(VerifyLoginView):
    """操作购物车, 添加购物车数据"""
    """
        1. 需要接收的参数
            sku_id count 
            从session中获取用户id

        2. 验证参数合法性
            a. 判断 为整数
            b. 要在数据库中存在商品
            c. 验证库存是否充足

        3. 操作数据库
            将购物车 保存到redis
            存储的时候采用的数据库类型为hash
            key           field value  field value
            cart_user_id  sku_id count

    """

    def post(self, request):
        # 1. 接收参数
        user_id = request.session.get("ID")
        sku_id = request.POST.get("sku_id")
        count = request.POST.get("count")

        # a.判断为整数
        try:
            sku_id = int(sku_id)
            count = int(count)
        except:
            return JsonResponse(json_msg(1, "参数错误!"))
        # b.要在数据库中存在商品
        try:
            goods_sku = Goods_Sku.objects.get(pk=sku_id)
        except Goods_Sku.DoesNotExist:
            return JsonResponse(json_msg(2, "商品不存在!"))

        # 判断库存
        if goods_sku.stock < count:
            return JsonResponse(json_msg(3, "库存不足!"))

        # 2. 操作数据
        # 创建连接
        r = get_redis_connection()
        # 处理购物车的 key
        cart_key = f"cart_{user_id}"

        # 添加
        # 获取购物车中已经存在的数量 加 上 需要添加 与 库存进行比较
        old_count = r.hget(cart_key, sku_id)  # 二进制
        if old_count is None:
            old_count = 0
        else:
            old_count = int(old_count)

        if goods_sku.stock < old_count + count:
            return JsonResponse(json_msg(3, "库存不足!"))

        # 将商品添加到购物车
        # r.hset(cart_key,sku_id,old_count + count)
        # ctrl + shift + u
        r.hincrby(cart_key, sku_id, count)

        # 获取购物车中的总数量
        cart_count = get_cart_count(request)

        # 3. 合成响应
        return JsonResponse(json_msg(0, "添加购物车成功", data=cart_count))

market/templates/cart/category.html
{% extends 'common/parent.html' %}
{% load static %}

{% block title %}
    商品列表
{% endblock %}

{% block header_css %}
    <style>
        .shop-list-mid .tit a {
            color: #909090;
            font-size: 1.4rem;
            display: -webkit-box;
            -webkit-line-clamp: 1;
            -webkit-box-orient: vertical;
            overflow: hidden;
            white-space: normal;
            text-overflow: ellipsis;
        }

        .list-price {
            background: url({% if order == 2 %}{% static 'images/order-bot.png' %}{% elif order == 3 %}{% static 'images/order-top.png' %}{% else %}{% static 'images/order.png' %}{% endif %}) no-repeat right center;
            padding-right: 20px;
            font-style: normal;
        }


    </style>
{% endblock %}

{% block header %}
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
        <div class="am-header-left am-header-nav">
            <a href="javascript:history.back()" class="">
                <i class="am-icon-chevron-left"></i>
            </a>
        </div>
        <form action="{% url 'search:haystack_search' %}" method="get">
            <div class="cate-search">
                <input type="text" name="q" value="" class="cate-input" placeholder="{{ query|default:'请输入您要的搜索的产品关键词' }}"/>
                <input type="submit" value="" class="cate-btn"/>
            </div>
        </form>
    </header>

{% endblock %}


{% block content %}
    <div style="height: 49px;"></div>
    <ul class="list-nav">
        <li {% if order == 0 %}
        class="current"
        {% endif %}><a href="{% url 'goods:分类列表'  cate_id 0 %}">综合</a></li>
        <li {% if order == 1 %}class="current"{% endif %}><a href="{% url 'goods:分类列表'  cate_id 1 %}">销量</a></li>
        <li {% if order == 2 or order == 3 %}class="current"{% endif %}><a id="price"  href="{% url 'goods:分类列表'  cate_id 2 %}"><i  class="list-price">价格</i></a></li>
        <li {% if order == 4 %}class="current"{% endif %}><a href="{% url 'goods:分类列表'  cate_id 4 %}">新品</a></li>
    </ul>
    <div class="content-list">
        <div class="list-left">
            {% for category in categorys %}
                <li {% if cate_id == category.pk %}class="current"{% endif %}>
                    <a href="{% url 'goods:分类列表' category.pk order %}">{{ category.cate_name }}</a>
                </li>
            {% endfor %}


        </div>
        <div class="list-right">
            <ul class="list-pro">

                {% for goods_sku in goods_skus %}
                <li>
                    <a href="{% url 'goods:详情' goods_sku.pk %}"><img src="{{ MEDIA_URL }}{{ goods_sku.logo }}" class="list-pic"/></a>
                    <div class="shop-list-mid" style="width: 65%;">
                        <div class="tit">
                            <a href="{% url 'goods:详情' goods_sku.pk %}">
                                {{ goods_sku.goods_spu.spu_name }}&emsp;{{ goods_sku.sku_name }}
                            </a>
                        </div>
                        <div class="am-gallery-desc">￥{{goods_sku.price}}</div>
                        <p>销量：{{goods_sku.salesvolume}}件</p>
                    </div>
                    <div class="list-cart">
                        <div class="d-stock ">
                            <a class="decrease">-</a>
                            <input id="num" readonly="" class="text_box" name="" type="text" value="0">
                            <a class="increase">+</a>
                        </div>
                    </div>
                </li>

                {% endfor %}




            </ul>
        </div>
    </div>

{% endblock %}


{% block footer %}
    <!--底部-->
    <div style="height: 55px;"></div>
    <div class="fix-bot">
        <div class="fix-bot-cart"><i id="cart_count">{{ cart_count }}</i></div>
        <a href="tureorder.html" class="list-js">去结算</a>
        <a href="tureorder.html" class="list-jsk">一键快购</a>
        <!--<div class="js-text">
           <p><b>￥217.80</b></p>
           <p class="js-car">购物满50元免运费</p>
     </div>-->
    </div>
{% endblock %}


{#{% block footer_js %}#}
{#    <script>#}
{#        //购物数量加减#}
{#        $(function () {#}
{#            $('.increase').click(function () {#}
{#                var self = $(this);#}
{#                var current_num = parseInt(self.siblings('input').val());#}
{#                current_num += 1;#}
{#                if (current_num > 0) {#}
{#                    self.siblings(".decrease").fadeIn();#}
{#                    self.siblings(".text_box").fadeIn();#}
{#                }#}
{#                self.siblings('input').val(current_num);#}
{#                update_item(self.siblings('input').data('item-id'));#}
{#            })#}
{#            $('.decrease').click(function () {#}
{#                var self = $(this);#}
{#                var current_num = parseInt(self.siblings('input').val());#}
{#                if (current_num > 0) {#}
{#                    current_num -= 1;#}
{#                    if (current_num < 1) {#}
{#                        self.fadeOut();#}
{#                        self.siblings(".text_box").fadeOut();#}
{#                    }#}
{#                    self.siblings('input').val(current_num);#}
{#                    update_item(self.siblings('input').data('item-id'));#}
{#                }#}
{#            })#}
{#        })#}
{##}
{#        $(function () {#}
{#            // 修改 标签上的地址值#}
{#            {% if order == 2 %}#}
{#                $("#price").attr('href','{% url "goods:分类列表" cate_id 3 %}');#}
{#            {% elif order == 3 %}#}
{#                $("#price").attr('href','{% url "goods:分类列表" cate_id 2 %}');#}
{#            {% endif %}#}
{#        })#}
{##}
{##}
{#    </script>#}
{#{% endblock %}#}


{% block footer_js %}
    <script>
        //购物数量加减
        $(function () {
            $('.increase').click(function () {
                var self = $(this);
                var current_num = parseInt(self.siblings('input').val());


                //完成ajax请求
                // 准备数据
                //sku_id 在input 上添加一个自定义属性 sku_id=1
                //找到input获取自定义的属性值
                var sku_id = self.siblings('input').attr('sku_id');
                var data = {
                    'csrfmiddlewaretoken':'{{ csrf_token }}',
                    'count':1,
                    'sku_id':sku_id
                };
                $.ajax({
                    type:"post",
                    url:"{% url 'cart:添加购物车' %}",
                    data:data,
                    dataType:"json",
                    success: function (data) {
                        if (data.code == 0){
                            //添加成功
                            current_num += 1;
                            if (current_num > 0) {
                                self.siblings(".decrease").fadeIn();
                                self.siblings(".text_box").fadeIn();
                            }
                            self.siblings('input').val(current_num);

                            //修改总数量
                            $("#cart_count").text(data.data);
                        }else if(data.code == 1){
                            //未登录陆,跳转到登录页面
                            if(confirm("没有登录,是否立即登录?")){
                                location.href = "{% url 'user:登录' %}"
                            }

                        }else {
                            alert(data.errmsg);
                        }
                    }
                });


            })
            $('.decrease').click(function () {
                var self = $(this);
                var current_num = parseInt(self.siblings('input').val());
                if (current_num > 0) {
                    current_num -= 1;
                    if (current_num < 1) {
                        self.fadeOut();
                        self.siblings(".text_box").fadeOut();
                    }
                    self.siblings('input').val(current_num);
                }
            })
        })


        $(function () {
            // 修改 标签上的地址值
            {% if order == 2 %}
                $("#price").attr('href','{% url "goods:分类列表" cate_id 3 %}');
            {% elif order == 3 %}
                $("#price").attr('href','{% url "goods:分类列表" cate_id 2 %}');
            {% endif %}
        })
    </script>
{% endblock %}