market/apps/goods/urls.py
from django.conf.urls import url

from goods.models import Category
from goods.views import DetailView, ListView, CategoryView,IndexView

urlpatterns = [
    url(r'^detail/(?P<id>\d+)/$',DetailView.as_view(),name='详情'),
    url(r'^cate/(?P<cate_id>\d*)_{1}(?P<order>\d?)\.html$', CategoryView.as_view(), name='分类列表'),
    url(r'^list/$',ListView.as_view(),name='店家列表'),
    url(r'^$',IndexView.as_view(),name='主页'),



]

market/market/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from user.views import RegisterView

urlpatterns = [
    #添加第三方插件
    # 上传部件自动调用的上传地址
    url(r'^ckeditor/', include("ckeditor_uploader.urls")),
    # 全文搜索框架
    url(r'^search/', include('haystack.urls', namespace='search')),

    #添加子路由
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('user.urls',namespace='user')),
    url(r'^goods/', include('goods.urls',namespace='goods')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
]

market/apps/goods/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models

# Create your models here.
from db.model_base import BaseModel

is_on_sale_choices = (
    (False, "下架"),
    (True, "上架"),
)

class Category(BaseModel):
    """商品分类表"""
    cate_name=models.CharField(verbose_name='分类名称',
                              max_length=20
    )
    brief = models.CharField(verbose_name='描述',
                             max_length=200,
                             null=True,
                             blank=True
                             )


    def __str__(self):
        return self.cate_name

    class Meta:
        verbose_name = "商品分类管理"
        verbose_name_plural = verbose_name


class Goods_Spu(BaseModel):
    """商品Spu表"""
    spu_name = models.CharField(verbose_name='商品SPU名称',
                                max_length=20, )
    #将之前详情修改使用富文本
    spu_detail = RichTextUploadingField(verbose_name='商品详情')

    def __str__(self):
        return self.spu_name

    class Meta:
        verbose_name = "商品SPU"
        verbose_name_plural = verbose_name


class Unit(BaseModel):
    """商品单位表"""
    unit_name=models.CharField(max_length=20,
                            verbose_name='单位名')

    def __str__(self):
        return self.unit_name

    class Meta:
        verbose_name="商品单位管理"
        verbose_name_plural=verbose_name

class Goods_Sku(BaseModel):
    """商品SKU表"""
    sku_name=models.CharField(max_length=100,
                              verbose_name='商品sku名称')

    brief=models.CharField(max_length=200,
                           null=True,
                           blank=True,
                           verbose_name='商品简介')

    price=models.DecimalField(max_digits=9,
                              decimal_places=2,
                              default=0,
                              verbose_name='价格')

    unit=models.ForeignKey(to="Unit",verbose_name="单位")

    stock=models.IntegerField(default=0,
                              verbose_name='库存')

    salesvolume=models.IntegerField(default=0,
                                    verbose_name='销量')

    #默认相册第一张作为封面图片
    logo=models.ImageField(upload_to='goods/%Y%m/%d',
                           verbose_name='封面图片')

    is_on_sale=models.BooleanField(choices=is_on_sale_choices,
                                   default=False,
                                   verbose_name='是否上架')
    category=models.ForeignKey(to="Category" ,
                                verbose_name='商品分类id')

    goods_spu=models.ForeignKey(to="Goods_Spu",
                                verbose_name='商品Spuid')

    def __str__(self):
        return self.sku_name

    class Meta:
        verbose_name = "商品SKU管理"
        verbose_name_plural = verbose_name


class Album(BaseModel):
    """商品相册表"""
    img_url=models.ImageField(upload_to='goods_gallery/%Y%m/%d',
                              verbose_name='相册地址'
                              )

    goods_sku=models.ForeignKey(to='Goods_Sku')

    class Meta:
        verbose_name = "商品相册管理"
        verbose_name_plural = verbose_name

    def __str__(self):
        return "商品相册:{}".format(self.img_url.name)


class Banner(BaseModel):
    """首页轮播表"""
    name= models.CharField(verbose_name="轮播活动名",
                            max_length=150,
                            )

    img_url = models.ImageField(verbose_name='轮播图片地址',
                                upload_to='banner/%Y%m/%d'
                                )

    order = models.SmallIntegerField(verbose_name="排序",
                                     default=0,
                                     )

    goods_sku = models.ForeignKey(to="Goods_Sku", verbose_name="商品SKU")

    class Meta:
        verbose_name = "轮播管理"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Activity(BaseModel):
    """首页活动表"""
    title = models.CharField(verbose_name='活动名称',
                             max_length=150)

    img_url = models.ImageField(verbose_name='活动图片地址',
                                upload_to='activity/%Y%m/%d'
                                )
    url_site = models.URLField(verbose_name='活动的url地址',
                               max_length=200)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "活动管理"
        verbose_name_plural = verbose_name


class ActivityZone(BaseModel):
    """
        首页活动专区
    """
    title = models.CharField(verbose_name='活动专区名称', max_length=150)
    brief = models.CharField(verbose_name="活动专区的简介",
                             max_length=200,
                             null=True,
                             blank=True,
                             )

    order = models.SmallIntegerField(verbose_name="排序",
                                     default=0,
                                     )

    is_on_sale = models.BooleanField(verbose_name="是否上线",
                                     choices=is_on_sale_choices,
                                     default=0,
                                     )

    goods_sku = models.ManyToManyField(to="Goods_Sku",verbose_name="商品")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "活动专区管理"
        verbose_name_plural = verbose_name

market/apps/goods/views.py
from django.shortcuts import render

# Create your views here.
from django.views import View

from db.base_view import VerifyLoginView
from goods.models import Goods_Spu, Goods_Sku, Category


class IndexView(View):
    def get(self,request):
        return render(request,'goods/index.html')

    def post(self,request):
        pass

class DetailView(View):
    def get(self,request,id):
        #获取商品sku的信息
        goods_sku=Goods_Sku.objects.get(pk=id)

        #渲染页面
        context={
            'goods_sku':goods_sku,
        }

        return render(request,'goods/detail.html',context=context)

    def post(self,request):
        pass

class CategoryView(View):
    """
            1. 页面刚加载的时候 显示的商品只 显示 排序 排第一的分类下的商品
            2. 点击哪个分类 就显示 对应分类下的商品
            3. 可以按照 销量,价格(降,升),添加时间,综合(pk) 排序 并且 是对应分类下的商品
                添加一个参数order:
                    0: 综合
                    1: 销量降
                    2: 价格升
                    3: 价格降
                    4: 添加时间降
                order_rule = ['pk', '-sale_num', 'price', '-price', '-create_time']
        """

    def get(self,request,cate_id,order):
        # 查询所有的分类
        categorys = Category.objects.filter(is_delete=False)
        #取出第一个分类
        # categorys.first()
        if cate_id == "" :
            category=categorys.first()
            cate_id=category.pk
        else:
            #根据分类id查询对应id
            cate_id=int(cate_id)
            category = Category.objects.get(pk=cate_id)
        # 查询所有的商品
        goods_skus = Goods_Sku.objects.filter(is_delete=False,category=category)
        if order == "":
            order = 0
        order = int(order)

        order_rule = ['pk', '-salesvolume', 'price', '-price', '-create_time']
        goods_skus = goods_skus.order_by(order_rule[order])

        # if order ==0:
        #     goods_skus=goods_skus.oder_by("pk")
        #
        # elif order ==1:
        #     goods_skus=goods_skus.order_by("-salesvolume")
        #
        #
        # elif order == 2:
        #     goods_skus = goods_skus.order_by("price")
        #
        # elif order == 3:
        #     goods_skus = goods_skus.order_by("-price")
        #
        # elif order == 4:
        #     goods_skus = goods_skus.order_by("-create_time")

        context = {
            'categorys': categorys,
            'goods_skus': goods_skus,
            'cate_id':cate_id,
            "order":order,
        }

        return  render(request,'goods/category.html',context=context)

    def post(self,request):
        pass


class ListView(View):
    def get(self,request):
        return render(request,'goods/list.html')


    def post(self,request):
        pass

market/templates/goods/category.html
{% extends 'common/parent.html' %}
{% load static %}

{% block title %}
    商品列表
{% endblock %}

{% block head_css %}
    <style>
        .shop-list-mid .tit a {
            color: #909090;
            font-size: 1.4rem;
            display: -webkit-box;
            -webkit-line-clamp: 1;
            -webkit-box-orient: vertical;
            overflow: hidden;
            white-space: normal;
            text-overflow: ellipsis;
        }
    </style>
{% endblock %}

{% block header %}
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
        <div class="am-header-left am-header-nav">
            <a href="javascript:history.back()" class="">
                <i class="am-icon-chevron-left"></i>
            </a>
        </div>
        <div class="cate-search">
            <input type="text" class="cate-input" placeholder="请输入您要的搜索的产品关键词"/>
            <input type="button" class="cate-btn"/>
        </div>
    </header>
    <div style="height: 49px;"></div>
{% endblock %}


{% block content %}
    <ul class="list-nav">
        <li class="current"><a href="">综合</a></li>
        <li><a href="">销量</a></li>
        <li><a href=""><i class="list-price">价格</i></a></li>
        <li><a href="">新品</a></li>
    </ul>
    <div class="content-list">
        <div class="list-left">
            {% for category in categorys %}
                <li class="current"><a href="">{{ category.cate_name }}</a></li>
            {% endfor %}


        </div>
        <div class="list-right">
            <ul class="list-pro">

                {% for goods_sku in goods_skus %}
                <li>
                    <a href="{% url 'goods:详情' goods_sku.pk %}"><img src="{{ MEDIA_URL }}{{ goods_sku.logo }}" class="list-pic"/></a>
                    <div class="shop-list-mid" style="width: 65%;">
                        <div class="tit">
                            <a href="{% url 'goods:详情' goods_sku.pk %}">
                                {{ goods_sku.goods_spu.spu_name }}&emsp;{{ goods_sku.sku_name }}
                            </a>
                        </div>
                        <div class="am-gallery-desc">￥{{goods_sku.price}}</div>
                        <p>销量：{{goods_sku.salesvolume}}件</p>
                    </div>
                    <div class="list-cart">
                        <div class="d-stock ">
                            <a class="decrease">-</a>
                            <input id="num" readonly="" class="text_box" name="" type="text" value="0">
                            <a class="increase">+</a>
                        </div>
                    </div>
                </li>
                {% endfor %}




            </ul>
        </div>
    </div>
{% endblock %}


{% block footer %}
    <!--底部-->
    <div style="height: 55px;"></div>
    <div class="fix-bot">
        <div class="fix-bot-cart"><i>8</i></div>
        <a href="tureorder.html" class="list-js">去结算</a>
        <a href="tureorder.html" class="list-jsk">一键快购</a>
        <!--<div class="js-text">
           <p><b>￥217.80</b></p>
           <p class="js-car">购物满50元免运费</p>
     </div>-->
    </div>
{% endblock %}


{% block footer_js %}
    <script>
        //购物数量加减
        $(function () {
            $('.increase').click(function () {
                var self = $(this);
                var current_num = parseInt(self.siblings('input').val());
                current_num += 1;
                if (current_num > 0) {
                    self.siblings(".decrease").fadeIn();
                    self.siblings(".text_box").fadeIn();
                }
                self.siblings('input').val(current_num);
                update_item(self.siblings('input').data('item-id'));
            })
            $('.decrease').click(function () {
                var self = $(this);
                var current_num = parseInt(self.siblings('input').val());
                if (current_num > 0) {
                    current_num -= 1;
                    if (current_num < 1) {
                        self.fadeOut();
                        self.siblings(".text_box").fadeOut();
                    }
                    self.siblings('input').val(current_num);
                    update_item(self.siblings('input').data('item-id'));
                }
            })
        })

    </script>
{% endblock %}

market/templates/goods/detail.html
{% extends 'common/parent.html' %}
{% load static %}

{% block title %}
商品详情
{% endblock %}

{% block header_css %}
<style>
			.am-slider-default .am-control-nav{ text-align: center;}
			.am-slider-default .am-control-nav li a.am-active{ background: #cb2527;}
			.am-slider-default .am-control-nav li a{ border: 0; width: 10px; height: 10px;}
		</style>
{% endblock %}

{% block header_js %}
<script>
        	function changeImage(){
              document.getElementById("imgflag").src="images/redherat.png";
           }
        </script>
{% endblock %}



{% block header %}



<header data-am-widget="header" class="am-header am-header-default sq-head ">
			<div class="am-header-left am-header-nav">
				<a href="javascript:history.back()" class="">
					<i class="am-icon-chevron-left"></i>
				</a>
			</div>
			<h1 class="am-header-title">
  	            <a href="" class="">商品详情</a>
            </h1>
	    </header>
{% endblock %}

{% block content %}
<div style="height: 49px;"></div>
	    <!--图片轮换-->
		<div class="am-slider am-slider-default" data-am-flexslider id="demo-slider-0">
		  <ul class="am-slides">
              {% for album in goods_sku.album_set.all %}
                    <li><img src="{{ MEDIA_URL }}{{ album.img_url }}" /></li>
{#		            <li><img src="{% static 'images/pic.png' %}" /></li>#}
              {% endfor %}
		  </ul>
		</div>
		<div class="detal-info" style="position: relative; width: 100%;">
			<p>{{ goods_sku.goods_spu.spu_name}}&emsp;{{ goods_sku.sku_name}}</p>
			<h2>商城价：<span>￥{{goods_sku.price}}</span></h2>
			<div class="heart">
				<img src="{% static 'images/herat.png' %}" width="25" id="imgflag" onclick="changeImage()" />
				<p>收藏</p>
			</div>
		</div>
		<div class="d-amount">
        	<h4>数量：</h4>
            <div class="d-stock">
              <a class="decrease">-</a>
                <input id="num" readonly="" class="text_box" name="" type="text" value="1">
                <input id="id" type="hidden" value="644">
                <a class="increase">+</a>
               <span id="dprice" class="price" style="display:none"> 36</span>
            </div>
        </div>
        <div style="background: #eee; height: 10px;"></div>
        <div class="am-tabs detail-list" data-am-tabs>
		  <ul class="am-tabs-nav am-nav am-nav-tabs">
		    <li class="am-active"><a href="#tab1">商品详情</a></li>
		    <li><a href="#tab2">商品评论</a></li>
		  </ul>

		  <div class="am-tabs-bd">
		    <div class="am-tab-panel am-fade am-in am-active detail " id="tab1" >
		            {{ goods_sku.goods_spu.spu_detail |safe}}

		    </div>
		    <div class="am-tab-panel am-fade detail " id="tab2">
		         <!--<div class="comment">
		         	<span>好评：</span>
		         	<div class="com-good"></div>
		         	<span>100%</span>
		         </div>
		         <div class="comment">
		         	<span>中评：</span>
		         	<div class="com-bad"></div>
		         	<span>0%</span>
		         </div>
		         <div class="comment">
		         	<span>差评：</span>
		         	<div class="com-bad"></div>
		         	<span>0%</span>
		         </div>-->
		         <ul class="comment-list">
		           <li class="current"><a href="">全部</a></li>
		           <li><a href="">好评（20）</a></li>
		           <li><a href="">中评（5）</a></li>
		           <li><a href="">差评（0）</a></li>
		         </ul>
		         <ul class="comment-pic">
		         	<li>
		         		<div class="tit">
		         			<img src="{% static 'images/tx.png' %}" class="tx" />
		         			<span>songke2014</span>
		         			<i> [2016-01-01]</i>
		         		</div>
		         		<div class="comment-con">
		         			买了些给家人，都说不错！
		         		</div>
		         	</li>
		         	<li>
		         		<div class="tit">
		         			<img src="{% static 'images/tx.png' %}" class="tx" />
		         			<span>songke2014</span>
		         			<i> [2016-01-01]</i>
		         		</div>
		         		<div class="comment-con">
		         			买了些给家人，都说不错！
		         		</div>
		         	</li>
		         </ul>
		    </div>
		  </div>
		</div>





{% endblock %}

{% block footer %}
	<!--底部-->
 <div style=" height: 55px;"></div>
 <ul class="fix-shopping">
 	<li><a href="shopcart.html" class="join">加入购物车</a></li>
 	<li><a href="tureorder.html" class="imm-buy">立即购买</a></li>
 </ul>
{% endblock %}

{% block footer_js %}
<script>
	//购物数量加减
	$(function(){
		$('.increase').click(function(){
			var self = $(this);
			var current_num = parseInt(self.siblings('input').val());
			current_num += 1;
			self.siblings('input').val(current_num);
			update_item(self.siblings('input').data('item-id'));
		})
		$('.decrease').click(function(){
			var self = $(this);
			var current_num = parseInt(self.siblings('input').val());
			if(current_num > 1){
				current_num -= 1;
				self.siblings('input').val(current_num);
				update_item(self.siblings('input').data('item-id'));
			}
		})
	})
</script>



    <script src="{%static 'js/jquery.min.js' %}"></script>
    <script src="{%static 'js/amazeui.min.js' %}"></script>
{% endblock %}
 
 
 
 

market/templates/goods/index.html
{% extends 'common/parent.html' %}
{% load static %}
{% block title %}
主页
{% endblock %}

{% block header_js %}
<script src="{% static 'js/popup.mini.js' %}"></script>
{% endblock %}

{% block header %}
<header data-am-widget="header" class="am-header am-header-default sq-head1">
			<div class="am-header-left am-header-nav">
		        <p class="" style="color: #fff;">
			        <img src="{% static 'images/city.png' %}" />
			        <p style="font-size: 12px; margin-top: -35px;"id="info">全国</p>
			    </p>
		   </div>
			<h1 class="am-header-title1">
		        <div class="search-box">
		           <a href="{% url 'search:haystack_search' %}" class="index-search">IPhone XS MAX</a>
		         <!--  <input type="submit" value="" class="search-icon" /> -->
		        </div>
		    </h1>
			<div class="am-header-right am-header-nav">
			    <a href="tidings.html" class="">
		         <div class="messgae"><span>10</span></div>
		        </a>
			</div>
        </header>
{% endblock %}

{% block content %}

<div style="height: 49px;"></div>
<!--图片轮换-->
<div class="am-slider am-slider-default" data-am-flexslider id="demo-slider-0">
  <ul class="am-slides">
    <li><img src="{% static 'images/banner.png' %}" /></li>
    <li><img src="{% static 'images/banner.png' %}" /></li>
  </ul>
</div>
<!--导航-->
 <ul class="sq-nav">
      <li>
        <div class="am-gallery-item">
            <a href="recharge.html" class="">
              <img src="{% static 'images/icon.png' %}" />
              <p>充值</p>
            </a>
        </div>
      </li>
      <li>
        <div class="am-gallery-item">
            <a href="javascript:;" class="index-qd">
              <img src="{% static 'images/icon1.png' %}" />
              <p>签到</p>
            </a>
        </div>
      </li>
      <li>
        <div class="am-gallery-item">
            <a href="yhq.html" class="">
              <img src="{% static 'images/icon2.png' %}" />
              <p>红包</p>
            </a>
        </div>
      </li>
      <li>
        <div class="am-gallery-item">
            <a href="" class="">
              <img src="{% static 'images/icon3.png' %}" />
              <p>即将上线</p>
            </a>
        </div>
      </li>
  </ul>
  <ul class="sq-nav1">
  	<li>
        <div class="am-gallery-item">
            <a href="speed.html" class="">
              <img src="{% static 'images/icon4.png' %}" />
              <p>零食飞速</p>
            </a>
        </div>
      </li>
      <li>
        <div class="am-gallery-item">
            <a href="{% url 'goods:分类列表' '' ''%}" class="">
              <img src="{% static 'images/icon5.png' %}" />
              <p>超市</p>
            </a>
        </div>
      </li>

  </ul>
  <div class="h-line"></div>
  <!--不规则展示-->
  <div class="index-product">
  	<div class="index-pro-lf"><a href=""><img src="{% static 'images/s1.png' %}"/></a></div>
  	<div class="index-pro-lr"><a href=""><img src="{% static 'images/s2.png' %}"/></a></div>
  </div>
  <div class="product-bot">
  	<div class="product-bot-lf"><a href=""><img src="{% static 'images/s3.png' %}"/></a></div>
  	<div class="product-bot-lr">
  		<div class="top"><a href=""><img src="{% static 'images/s4.png' %}"/></a></div>
  		<div class="bot">
  			<div class="bot-lf"><a href=""><img src="{% static 'images/s5.png' %}"/></a></div>
  			<div class="bot-lr"><a href=""><img src="{% static 'images/s6.png' %}"/></a></div>
  		</div>
  	</div>
  </div>
  <!--不规则展示-->
  <div class="h-line"></div>
  <!-- 特色专区-->
  <div class="sq-title">
 	<img src="{% static 'images/ts.png' %}" width="26"/>
 	特色专区
  </div>
  <ul data-am-widget="gallery" class="am-gallery pro-list am-avg-sm-2 am-avg-md-2 am-avg-lg-4 am-gallery-default"  >
      <li>
        <div class="am-gallery-item">
            <a href="detail.html" class="">
              <img src=" {% static 'images/test.png' %}" />
                <h3 class="am-gallery-title">猪骨头棒新鲜生鲜肉制品猪大骨头筒骨熬汤佳品500g</h3>
                <div class="am-gallery-desc">￥52</div>
            </a>
        </div>
      </li>
      <li>
        <div class="am-gallery-item">
            <a href="detail.html" class="">
              <img src=" {% static 'images/test1.png' %}" />
                <h3 class="am-gallery-title">冻品批发大江鸡腿 冷鲜鸡腿放心食材1kg 冷冻食材</h3>
                <div class="am-gallery-desc">￥39</div>
            </a>
        </div>
      </li>
        <li>
        <div class="am-gallery-item">
            <a href="detail.html" class="">
              <img src=" {% static 'images/test2.png' %}" />
                <h3 class="am-gallery-title">法国加力果12个装 进口新鲜水果 嘎啦苹果 包邮</h3>
                <div class="am-gallery-desc">￥45.8</div>
            </a>
        </div>
      </li>
      <li>
        <div class="am-gallery-item">
            <a href="detail.html" class="">
              <img src="{% static 'images/test21.png' %} " />
                <h3 class="am-gallery-title">法国加力果12个装 进口新鲜水果 嘎啦苹果 包邮</h3>
                <div class="am-gallery-desc">￥45.8</div>
            </a>
        </div>
      </li>
       <li>
        <div class="am-gallery-item">
            <a href="detail.html" class="">
              <img src="{% static 'images/test.png' %}" />
                <h3 class="am-gallery-title">猪骨头棒新鲜生鲜肉制品猪大骨头筒骨熬汤佳品500g</h3>
                <div class="am-gallery-desc">￥52</div>
            </a>
        </div>
      </li>
      <li>
        <div class="am-gallery-item">
            <a href="detail.html" class="">
              <img src="{% static 'images/test1.png' %} " />
                <h3 class="am-gallery-title">冻品批发大江鸡腿 冷鲜鸡腿放心食材1kg 冷冻食材</h3>
                <div class="am-gallery-desc">￥39</div>
            </a>
        </div>
      </li>
        <li>
        <div class="am-gallery-item">
            <a href="detail.html" class="">
              <img src=" {% static 'images/test2.png' %}" />
                <h3 class="am-gallery-title">法国加力果12个装 进口新鲜水果 嘎啦苹果 包邮</h3>
                <div class="am-gallery-desc">￥45.8</div>
            </a>
        </div>
      </li>
      <li>
        <div class="am-gallery-item">
            <a href="detail.html" class="">
              <img src=" {% static 'images/test21.png' %}" />
                <h3 class="am-gallery-title">法国加力果12个装 进口新鲜水果 嘎啦苹果 包邮</h3>
                <div class="am-gallery-desc">￥45.8</div>
            </a>
        </div>
      </li>
  </ul>
<!--签到-->
<div class="qd-box">
	<div class="popup-title">
			<span>签到成功</span>
			<div class="popup-close"><i class="iconfont">&#xe602</i></div>
	</div>
	<div class="dq-text">
		<img src="{% static 'images/qiandao.png' %}" width="40" />&nbsp; 您已连续签到3天
	</div>
</div>
<!--签到-->


{% endblock %}

{% block footer %}
<!--底部-->
 <div style="height: 55px;"></div>
 <div data-am-widget="navbar" class="am-navbar am-cf am-navbar-default sq-foot am-no-layout" id="">
      <ul class="am-navbar-nav am-cf am-avg-sm-5">
          <li>
            <a href="index.html" class="curr">
                <span class="am-icon-home"></span>
                <span class="am-navbar-label">首页</span>
            </a>
          </li>
          <li>
            <a href="message.html" class="">
                <span class="am-icon-comments"></span>
                <span class="am-navbar-label">动态</span>
            </a>
          </li>
          <li>
            <a href="shopcart.html" class="">
                <span class="am-icon-shopping-cart"></span>
                <span class="am-navbar-label">购物车</span>
            </a>
          </li>
          <li>
            <a href="allorder.html" class="">
                <span class="am-icon-file-text"></span>
                <span class="am-navbar-label">订单</span>
            </a>
          </li>

          <li>
            <a href="member.html" class="">
                <span class="am-icon-user"></span>
                <span class="am-navbar-label">我的</span>
            </a>
          </li>
      </ul>
</div>


{% endblock %}

{% block footer_js %}
<script type='text/javascript'>
	(function(){
		 new PopUp_api({el:'.index-qd',html:'.qd-box'});
	})()
</script>

<script src="{%static 'js/jquery.min.js' %}"></script>
<script src="{%static 'js/amazeui.min.js' %}"></script>
<script type="text/javascript"
        src="https://webapi.amap.com/maps?v=1.4.12&key=5ca6447d8cdacbc64b2c1f14ffd78268&plugin=AMap.CitySearch"></script>
<script type="text/javascript">
    //获取用户所在城市信息
    function showCityInfo() {
        //实例化城市查询类
        var citysearch = new AMap.CitySearch();
        //自动获取用户IP，返回当前城市
        citysearch.getLocalCity(function (status, result) {
            if (status === 'complete' && result.info === 'OK') {
                if (result && result.city && result.bounds) {
                    var cityinfo = result.city;
                    var citybounds = result.bounds;
                    document.getElementById('info').innerHTML = cityinfo;
                    //地图显示当前城市
                    map.setBounds(citybounds);
                }
            } else {
                document.getElementById('info').innerHTML = result.info;
            }
        });
    }

    showCityInfo();
</script>




{% endblock %}