market/apps/user/urls.py
from django.conf.urls import url

from user.views import RegisterView, LoginView, MemberView, ForgetView, SendMsm,InfoView

urlpatterns = [
    url(r'^register/', RegisterView.as_view(),name='注册'),
    url(r'^login/',LoginView.as_view(),name='登录'),
    url(r'^member/', MemberView.as_view(),name='个人中心'),
    # url(r'^changepwd/', ChangePasswordView.as_view(),name='修改密码'),
    url(r'^forget/', ForgetView.as_view(),name='忘记密码'),
    url(r'^sendMsg/',SendMsm.as_view(),name='发送短信验证码'),
    url(r'^info/',InfoView.as_view(),name='个人资料'),
]

market/market/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from user.views import RegisterView

urlpatterns = [
    #添加第三方插件
    # 上传部件自动调用的上传地址
    url(r'^ckeditor/', include("ckeditor_uploader.urls")),
    # 全文搜索框架
    url(r'^search/', include('haystack.urls', namespace='search')),

    #添加子路由
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('user.urls',namespace='user')),
    url(r'^goods/', include('goods.urls',namespace='goods')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
]

market/apps/user/forms.py
import hashlib

from django import forms
from django.core.validators import RegexValidator
from django_redis import get_redis_connection

from user.models import MarkUser


class RegisterModelForm(forms.ModelForm):
    password = forms.CharField(max_length=16,
                               min_length=6,
                               # error_messages获取表单字段错误信息
                               error_messages={
                                   'required': '密码不能为空',
                                   'max_length': '最大长度为16位',
                                   'min_length': '最小长度为6位',
                               })  # CharField用于接收文本
    repassword = forms.CharField(error_messages={
        'required': '请确认密码',
    })
    captcha=forms.CharField(max_length=6,
                            error_messages={
                                'required':'验证码必须填写'
                            })

    agree =forms.BooleanField(error_messages={
                                'required':'必须同意用户协议'
    })

    class Meta:
        # 关联模型
        model = MarkUser
        # 验证需要的字段
        fields = ['tel', ]
        error_messages = {'tel':
                              {'required': '手机号码不能为空'}
                          }

    def clean_tel(self):
        # 验证手机号码是否重复
        # 获取清洁后的数据tel
        tel = self.cleaned_data.get('tel')
        # 去数据库查询数据是否存在
        repeat_judge = MarkUser.objects.filter(tel=tel).exists()
        if repeat_judge:
            # 抛出一个错误信息
            raise forms.ValidationError('手机号码已经注册')
        else:
            return tel



    def clean(self):
        # 验证密码是否重复
        # 1.获取两次的密码数据
        pwd = self.cleaned_data.get('password')
        pwd1 = self.cleaned_data.get('repassword')
        if pwd and pwd1 and pwd != pwd1:
            raise forms.ValidationError('两次密码不一致')


        #综合校验
        # 验证用户传入验证码跟redis中的是否一样
        try:
            captcha = self.cleaned_data.get('captcha')
            tel = self.cleaned_data.get('tel', '')
            # 获取redis中的
            r = get_redis_connection()
            random_code = r.get(tel)  # 二进制, 转码
            random_code = random_code.decode('utf-8')
            # 比对
            if captcha and captcha != random_code:
                raise forms.ValidationError({"captcha": "验证码输入错误!"})
        except:
            raise forms.ValidationError({"captcha": "验证码输入错误!"})

        # 返回清洁后的数据
        return self.cleaned_data





class LoginModelForm(forms.ModelForm):
    class Meta:
        # 关联模型
        model = MarkUser
        # 需要验证的字段
        fields = ['tel', 'password']
        # 验证字段是否为空
        error_messages = {
            'tel': {
                'required': '请填写手机号'
            },
            'password': {
                'required': '请填写密码'
            }
        }

    def clean(self):
        # 获取用户名和密码
        tel = self.cleaned_data.get('tel')
        password = self.cleaned_data.get('password')
        # 根据获取数据查询数据库
        # get获取数据库如果没有会报错，所以加try
        # 查询数据库中tel用户的所有信息
        try:
            user = MarkUser.objects.get(tel=tel)
        except MarkUser.DoesNotExist:
            raise forms.ValidationError({'tel': '手机号码错误'})

        # 验证密码md5正向不可逆所以验证密码必须给获取密码数据进行编码加密
        h = hashlib.md5(self.cleaned_data.get('password').encode('utf-8'))
        if user.password != h.hexdigest():
            raise forms.ValidationError({'password': '密码错误'})

        # 将用户信息保存到cleaned_data中
        self.cleaned_data['user'] = user
        return self.cleaned_data


# class ChangePasswordModelForm(forms.ModelForm):
#     password = forms.CharField(error_messages={
#                                     'required':'请输入密码'
#     })
#     class Meta:
#         #关联模型
#         model = MarkUser
#         #需要验证的字段
#         fields=['password',]
#         # 验证字段是否为空
#         error_messages = {
#             'password': {
#                 'required': '请填写密码'
#             }
#         }
#
#     def clean_tel(self):
#         #验证手机号码是否存在
#         #获取清洁后的数据tel
#         tel=self.cleaned_data.get('tel')
#         #去数据库查询数据是否存在
#         exists_judge=MarkUser.objects.filter(tel=tel).exists()
#         if exists_judge:
#             #返回一个tel
#             return tel
#         else:
#             raise forms.ValidationError('手机号码不存在')
#
#
#     def clean(self):
#         #验证密码是否重复
#         #1.获取两次的密码数据
#         pwd=self.cleaned_data.get('newpassword1')
#         pwd1=self.cleaned_data.get('newrepassword2')
#         if pwd and pwd1 and pwd != pwd1:
#             raise forms.ValidationError('两次密码不一致')
#         else:
#             #返回清洁后的数据
#             return self.cleaned_data
#
#      def clean_password(self):
#         tel=self.cleaned_data.get('tel')
#         try:
#             user=MarkUser.objects.get(tel=tel)
#         except MarkUser.DoesNotExist:
#             raise forms.ValidationError({'tel':'手机号码错误'})
#
#         #验证密码md5正向不可逆所以验证密码必须给获取密码数据进行编码加密
#         h=hashlib.md5(self.cleaned_data.get('password').encode('utf-8'))
#         if user.password !=h.hexdigest():
#             raise forms.ValidationError({'password':'密码错误'})
#
#         else:
#             pass
class ForgetModelForm(forms.ModelForm):
    password = forms.CharField(max_length=16,
                               min_length=6,
                               # error_messages获取表单字段错误信息
                               error_messages={
                                   'required': '密码不能为空',
                                   'max_length': '最大长度为16位',
                                   'min_length': '最小长度为6位',
                               })  # CharField用于接收文本
    repassword = forms.CharField(error_messages={
        'required': '请确认密码',
    })

    class Meta:
        model = MarkUser
        fields = ['tel']
        error_messages = {
            'tel': {
                'required': '请输入手机号码'
            }
        }

    def clean_tel(self):
        # 验证手机号码是否重复
        # 获取清洁后的数据tel
        tel = self.cleaned_data.get('tel')
        # 去数据库查询数据是否存在
        tel_judge = MarkUser.objects.filter(tel=tel).exists()
        if  not tel_judge:
            raise forms.ValidationError('手机号码不存在')
        else:
            return tel_judge

    def clean_password(self):
        # 验证密码是否重复
        # 1.获取两次的密码数据
        pwd = self.cleaned_data.get('password')
        pwd1 = self.cleaned_data.get('repassword')
        if pwd and pwd1 and pwd != pwd1:
            raise forms.ValidationError('两次密码不一致')
        else:
            # 返回清洁后的数据
            return self.cleaned_data


class InfoForm(forms.Form):
    nickname=forms.CharField(max_length=10,
                             min_length=3,
                             error_messages={
                                 'max_length':'最大昵称长度为10',
                                 'min_length':'最少起3字以上的昵称',
                             })

market/apps/user/views.py
import hashlib
import random
import uuid

from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect

# Create your views here.
from django.views import View

from db.base_view import VerifyLoginView
from user.forms import RegisterModelForm, LoginModelForm, ForgetModelForm, InfoForm
from user.helper import send_sms
from user.models import MarkUser
import re
from django_redis import get_redis_connection


class RegisterView(View):
    def get(self,request):
        return render(request,'user/reg.html')

    def post(self,request):
        #接收参数
        data=request.POST
        # print(data) 断点：得到 html 中name名为tel password repassword数据
        #实例化表单对象
        #把数据传入验证表单
        register_form=RegisterModelForm(data)
        #验证合法性
        if register_form.is_valid():
            #合法
            #获取清洁后的数据
            cleaned_data=register_form.cleaned_data
            # 操作数据库
            #创建一个用户
            user=MarkUser()
            user.tel=cleaned_data.get('tel')
            #对清洁后的密码加密设置编码
            h=hashlib.md5(cleaned_data.get('password').encode('utf-8'))
            user.password=h.hexdigest()
            user.save()
            return redirect('user:登录')
            # return HttpResponse("合法")

        # 合成响应
        else:
            # return HttpResponse("不合法")
            return render(request,'user/reg.html',{'form':register_form})


# class LoginView(View):
#     def get(self,request):
#         return  render(request,'user/login.html')
#
#     def post(self,request):
#         #接收参数
#         data=request.POST
#         #创建模型对象
#         login_form=LoginModelForm(data)
#         #验证合法性
#         if login_form.is_valid():
#             #从表单中得到清洁后用户信息
#             user=login_form.cleaned_data.get('user')
#             #保存所需信息到seesion中
#             request.session['ID'] =user.pk
#             request.session['tel']=user.tel
#             request.session['head']=user.head
#             #关闭浏览器就消失
#             request.session.set_expiry(0)
#
#             return redirect('user:个人中心')
#
#
#             #合法
#             # return  HttpResponse("合法")
#         else:
#             #合成响应
#             return render(request,'user/login.html',{'form':login_form})


class LoginView(View):
    """登录视图"""

    def get(self, request):
        return render(request, 'user/login.html')

    def post(self, request):
        # 获取数据
        data = request.POST
        # 验证数据合法性
        login_form = LoginModelForm(data)
        if login_form.is_valid():
            # 操作数据库
            # 保存登录标识到session中, 单独创建一个方法保存, 更新个人资料
            user = login_form.cleaned_data['user']
            request.session['ID'] = user.pk
            request.session['tel'] = user.tel
            # request.session['head'] = user.head
            request.session.set_expiry(0) #关闭浏览器就消失
            # login(request, user)

            referer = request.session.get('referer')
            if referer:
                # 跳转回去
                # 删除session
                del request.session['referer']
                return redirect(referer)
            else:
                # 合成响应, 跳转到个人中心
                return redirect('user:个人中心')
        else:
            return render(request, 'user/login.html', {'form': login_form})




class MemberView(VerifyLoginView):
    def get(self,request):
        return render(request,'user/member.html')

    def post(self,request):
        pass




class ForgetView(View):
    def get(self,request):
        return render(request,'user/forgetpassword.html')

    def post(self,request):
        #获取数据
        data=request.POST
        forget_form=ForgetModelForm(data)
        if forget_form.is_valid():

            tel=ForgetModelForm.cleaned_data.get('tel')
            password=ForgetModelForm.cleaned_data.get('password')
            h = hashlib.md5(ForgetModelForm.cleaned_data.get('password').encode('utf-8'))

            user=MarkUser()
            user.objects.filter(tel=tel).update(password=h.hexdigest())
            return redirect('user:个人中心')
            #合法
            #操作数据库

            # MarkUser.objects.
            return redirect('user:登录')
        else:
            return render(request,'user/forgetpassword.html',{'form':forget_form})

        # return HttpResponse('ko')



# class ChangePasswordView(View):
#     def get(self,request):
#         return render(request,'user/forgetpassword.html')
#
#     def post(self,request):
#         pass
#         #接收参数
#         data=request.POST
#         Change_form=ChangePasswordModelForm(data)
#
#         #操作数据库
#         #合成响应

class SendMsm(View):
    """发送短信"""
    def get(self,request):
        pass

    def post(self,request):
        #1.接受参数
        tel=request.POST.get('tel','')
        # 匹配不到位none 匹配到是一个对象
        rs=re.search('^1[3-9]\d{9}$',tel)
        if rs is None:
            return JsonResponse({'error':1,'errmsg':'电话号码格式错误'})

        #2.处理数据
        #模拟，后再接入运营商
        """
            1.生成随机的验证码
            2.保存验证码道redis
            3.接入运营商
        """
        #1.生成随机验证码
        #列表推倒式是个列表
        # [str(random.randint(0,9)for _ in range(6))]
        #拼接字符串
        random_code="".join([str(random.randint(0,9)) for _ in range(6)])


        print('**************随机验证码为****{}********************'.format(random_code))

        #2.保存验证码到redis中
        #获取连接
        r=get_redis_connection()
        r.set(tel,random_code)
        #保存手机发送验证码次数不超过5次
        #受限获取当前手机号码发送的次数

        r.expire(tel, 60)  # 设置60秒后过期

        # 首先获取当前手机号码的发送次数
        key_times = "{}_times".format(tel)
        now_times = r.get(key_times)  # 从redis获取的二进制,需要转换
        # print(int(now_times))
        if now_times is None or int(now_times) < 5:
            # 保存手机发送验证码的次数, 不能超过5次
            r.incr(key_times)
            # 设置一个过期时间
            r.expire(key_times, 3600)  # 一个小时后再发送
        else:
            # 返回,告知用户发送次数过多
            return JsonResponse({"error": 1, "errmsg": "发送次数过多"})


        #接入运营商
        # __business_id = uuid.uuid1()
        # params = "{\"code\":\"%s\",\"product\":\"景一机车服店\"}"% random_code
        # print(send_sms(__business_id,tel, "注册验证", "SMS_2245271", params))
        # print(rs.decode('utf-8'))
            # >>>3. 接入运营商
        # __business_id = uuid.uuid1()
        # params = "{\"code\":\"%s\",\"product\":\"景一机车服店\"}" % random_code
        # # print(params)
        # rs = send_sms(__business_id, tel, "注册验证", "SMS_2245271", params)

        # 接入运营商
        __business_id = uuid.uuid1()
        params = "{\"code\":\"%s\",\"product\":\"湖南铁赖瓜子店\"}" % random_code
        print(send_sms(__business_id, tel, "注册验证", "SMS_2245271", params))
        # print(rs.decode('utf-8'))

        #3.合成响应
        return JsonResponse({'error':0})


class InfoView(VerifyLoginView):
    def get(self, request):
        # 获取session中的用户id
        user_id = request.session.get("ID")
        # 获取用户资料
        user = MarkUser.objects.get(pk=user_id)

        # 渲染到页面
        context = {
            'user': user
        }
        return render(request, 'user/infor.html', context=context)


    def post(self,request):
        #接收参数
        data=request.POST
        head = request.FILES.get('head')
        user_id = request.session.get('ID')

        info_form=InfoForm(data)
        if info_form.is_valid():
            #合法
            # 操作数据
            user = MarkUser.objects.get(pk=user_id)
            user.nickname=info_form.cleaned_data.get('nickname')
            user.gender = request.POST.get('gender')
            user.school_name = request.POST.get('school_name')
            user.hometown = request.POST.get('hometown')
            user.address = request.POST.get('address')
            user.birth_date = request.POST.get('birth_data')
            if head is not None:
                user.head=head
            user.save()

            #同时修改session
            # 保存所需信息到seesion中
            request.session['ID'] = user.pk
            request.session['tel'] = user.tel
            request.session['head'] = user.head
            # 关闭浏览器就消失
            request.session.set_expiry(0)

            return redirect('user:个人资料')

            #操作数据

market/templates/user/forgetpassword.html
{% extends 'common/parent.html' %}
{% load static%}
{% block title %}
忘记密码
{% endblock %}
{% block header %}
<header data-am-widget="header" class="am-header am-header-default sq-head ">
			<div class="am-header-left am-header-nav">
				<a href="javascript:history.back()" class="">
					<i class="am-icon-chevron-left"></i>
				</a>
			</div>
			<h1 class="am-header-title">
  	            <a href="" class="">忘记密码</a>
            </h1>
	    </header>
{% endblock %}
{% block content %}
<div style="height: 49px;"></div>
        <form action="" method="post">
            {% csrf_token %}
	    <input type="text" name="tel" value="{{ request.POST.tel}}" placeholder="请输入手机号" class="login-password">
        <p class="am-text-danger">{{ form.errors.tel.0 }}</p>
{#	    <div class="yzm">#}
{#	    	<input type="text" class="reg-yzm" placeholder="输入验证码" />#}
{#	    	<input type="button" class="yzm-hq" value="获取验证码" />#}
{#	    </div>#}
	    <input type="password" name="password"  placeholder="请输入密码" class="login-password">
        <p class="am-text-danger">{{ form.errors.password.0 }}</p>

	    <input type="password" name="repassword"  placeholder="确认密码" class="login-name">
        <p class="am-text-danger">{{ form.errors.repassword.0 }}</p>
	    <input type="submit" class="login-btn" value="立即提交">
        <form/>

{% endblock %}

market/templates/user/infor.html
{% extends 'common/parent.html' %}
{% load static %}
{% block title %}
    个人资料
{% endblock %}

{% block head_css %}
    <link href="{% static 'css/check.css' %}" rel="stylesheet" type="text/css"/>
{% endblock %}

{% block header %}
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
        <div class="am-header-left am-header-nav">
            <a href="{% url 'user:个人中心' %}" class="">
                <i class="am-icon-chevron-left"></i>
            </a>
        </div>
        <h1 class="am-header-title">
            <a href="" class="">个人资料</a>
        </h1>
    </header>
    <div style="height: 49px;"></div>
{% endblock %}


{% block content %}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <ul class="safty1">
        <li>
            <i style="margin-top: 25px;">头像</i>
            <div class="infor-pic">
                <img src="{{ MEDIA_URL }}{{ user.head }}"/>
            </div>
        </li>
        <li>
            <input type="file" name="head">
        </li>
        <li>
            <i>昵称</i>
            <input class="infor-tele" name="nickname" value="{{ user.nickname|default:'' }}" placeholder="默认"/>
        </li>
        <li>

                <i>性别</i>
                <i class="infor-tele">
                    <label class="am-radio-inline">
                        <input type="radio" name="gender" checked="checked" value="1" data-am-ucheck>男
                    </label>
                    <label class="am-radio-inline">
                        <input type="radio" name="gender" value="2" data-am-ucheck>女
                    </label>
                </i>
            </a>
        </li>
        <li>

                <i>生日</i>
                <input class="infor-tele" name="birth_date"  value="" placeholder="出生日期"/>
            </a>
        </li>

    </ul>

    <div style="height: 10px; background: #efefef;"></div>
    <ul class="safty1">
        <li>
            <i>学校</i>
            <input class="infor-tele" name="school_name" value="{{ user.address }}"  placeholder="就读于哪个学校"/>
        </li>
        <li>
            <i>位置</i>
            <input class="infor-tele" name="address" value="{{ user.address }}" placeholder="详细地址"/>
        </li>
        <li>
            <i>故乡</i>
            <input class="infor-tele" name="hometown" value="{{ user.hometown }}" placeholder="来自哪里"/>
        </li>
        <li>
            <i>手机</i>
            <p class="infor-tele" value="{{user.tel}}"></p>
        </li>
        <li>
            <input type="submit" class="am-btn am-btn-warning" value="保存"/>
        </li>
    </ul>
    </form>
{% endblock %}

market/templates/user/login.html
{#{% extends 'common/parent.html' %}#}
{#{% load static %}#}
{#{% block title %}#}
{#登录#}
{#{% endblock %}#}
{##}
{#{% block header %}#}
{#<header data-am-widget="header" class="am-header am-header-default sq-head ">#}
{#    <div class="am-header-left am-header-nav">#}
{#        <a href="javascript:history.back()" class="">#}
{#            <i class="am-icon-chevron-left"></i>#}
{#        </a>#}
{#    </div>#}
{#    <h1 class="am-header-title">#}
{#        <a href="" class="">登录</a>#}
{#    </h1>#}
{#</header>#}
{#{% endblock %}#}
{##}
{##}
{#{% block content %}#}
{#    <form action="" method="post" class="form-horizontal">#}
{#     {% csrf_token %}#}
{#<div style="height: 49px;"></div>#}
{#<!--<div class="login-logo">#}
{#    <img src="images/logo.png" />#}
{#</div>-->#}
{#<div style="height: 3rem;"></div>#}
{#    <input type="text" name="tel" id="tel" placeholder="请输入用户名/手机号" class="login-name">#}
{#    <input type="password" name="password" id="password" placeholder="请输入密码" class="login-password">#}
{#    <input type="submit" class="login-btn" value="我要登录">#}
{#<div class="agree">#}
{#    <a href="{% url 'user:注册' %}">免费注册</a>#}
{#    <a href="forgetpassword.html" class="forget">忘记密码？</a>#}
{#</div>#}
{#<div class="line"></div>#}
{#<div class="line-text">第三方账号登录</div>#}
{#    <ul class="second-login">#}
{#        <li><a href=""><img src="  {% static 'images/wxlogin.png' %} "/></a></li>#}
{#        <li><a href=""><img src="  {% static 'images/qqlogin.png' %} "/></a></li>#}
{#        <li><a href=""><img src="  {% static 'images/sinalog.png' %} "/></a></li>#}
{#    </ul>#}
{#    </form>#}
{##}
{#{% endblock %}#}




{% extends 'common/parent.html' %}
{% load static %}

{% block title %}
    登录
{% endblock %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <input type="text" name="tel" id="tel" value="{{ request.POST.tel }}" placeholder="手机号" class="login-name">
        <p class="am-text-danger">{{ form.errors.tel.0 }}</p>
        <input type="password" name="password" id="password" placeholder="请输入密码" class="login-password">
        <p class="am-text-danger">{{ form.errors.password.0 }}</p>
        <input type="submit" class="login-btn" value="我要登录">
        <div class="agree">
            <a href="{% url 'user:注册' %}">免费注册</a>
            <a href="{% url 'user:忘记密码' %}" class="forget">忘记密码？</a>
        </div>
        <div class="line"></div>
        <div class="line-text">第三方账号登录</div>
        <ul class="second-login">
            <li><a href=""><img src="{% static 'images/wxlogin.png' %}"/></a></li>
            <li><a href=""><img src="{% static 'images/qqlogin.png' %}"/></a></li>
            <li><a href=""><img src="{% static 'images/sinalog.png' %}"/></a></li>
        </ul>
    </form>
{% endblock %}

market/templates/user/reg.html
{% extends 'common/parent.html' %}
{% load static %}

{% block title %}
注册
{% endblock %}

{% block header %}
<header data-am-widget="header" class="am-header am-header-default sq-head ">
    <div class="am-header-left am-header-nav">
        <a href="javascript:history.back()" class="">
            <i class="am-icon-chevron-left"></i>
        </a>
    </div>
    <h1 class="am-header-title">
        <a href="" class="">注册</a>
    </h1>
</header>
{% endblock %}

{% block content %}

<div style="height: 49px;"></div>
   <form action="" method="post" class="form-horizontal">
        {% csrf_token %}
       <!--<div class="login-logo">
       <img src="images/logo.png" />
</div>-->
<div style="height: 3rem;"></div>
    <input type="text" name="tel" id="tel" placeholder="请输入手机号" class="login-name">
       <p class="am-text-danger">{{ form.errors.tel.0 }}</p>
    <input type="password" name="password"  placeholder="请输入密码" class="login-password">
       <p class="am-text-danger">{{ form.errors.password.0 }}</p>
    <input type="password" name="repassword"  placeholder="确认密码" class="login-name">
       <p class="am-text-danger">{{ form.errors.repassword.0 }}</p>
<div class="yzm" style="margin-top: 1.5rem;">
    <input type="text" name="captcha" class="reg-yzm" placeholder="输入验证码" />
    <input type="button" class="yzm-hq" value="获取验证码" />

</div>
       <p class="am-text-danger">{{ form.errors.captcha.0 }}</p>
    <input type="submit" class="login-btn" value="立即注册">

<div class="agree">
    <input type="checkbox" name="agree" value="同意" checked="">&nbsp;同意
    <p class="am-text-warning">{{ form.errors.agree.0 }}</p>
    <a href="" class="xy">《用户协议》</a>
    <div class="r-login">已有账号，请<a href="login.html" class="l-login">登录</a></div>
</div>
    </form>

{% endblock %}

{% block footer_js %}
    <script type="application/javascript">
        $(function(){
            //加载完网页才执行
            //1.绑定点击事件
            $('.yzm-hq').on('click',function(){
              //测试
              {#console.debug('ceshi')#}
                //2.获取手机号码
                var tel = $('#tel').val();
                var reg= /^1[3-9]\d{9}$/;

                {#reg.test(tel)#}
                //验证手机号码
                {#console.debug( reg.test(tel))#}
                if (!reg.test(tel)){
                    //验证失败
                    alert("手机号码格式错误");
                    return;
                }
                //为了让ajax里用到按钮定义一个变量
                var self =this;
                //3.发送ajax请求
                $.ajax({
                    type:'post',
                    url:'{% url "user:发送短信验证码" %}',
                    data:{'tel':tel,'csrfmiddlewaretoken':'{{csrf_token}}'
                    },
                    dataType:'json',
                    success:function (data) {
                        console.debug(data)
                        //4判断是否发送成功
                        if(data.error == 0){
                            //1.按钮变灰
                            $(self).css("background-color","gray");
                            //2.按钮不能再点击
                            $(self).prop('disabled',true);

                            //3.开始倒计时
                            var time = 60;
                            var msg = time + "秒后重新发送";
                            $(self).val(msg);
                            var timer = window.setInterval(function () {
                                time -= 1;
                                if (time == 0){
                                    //1. 按钮颜色变绿
                                    $(self).css("background-color","#76bb2a");
                                    //2. 按钮能再点击
                                    $(self).prop('disabled',false);
                                    //3. 返回到原来的提示文字
                                    $(self).val("获取验证码");
                                    //4. 清除定时
                                    window.clearInterval(timer);
                                    //返回
                                    return;
                                }
                                msg = time + "秒后重新发送";
                                $(self).val(msg);
                            },1000);


                        }else{
                            alert('短信验证码发送失败！')
                        }
                        
                    }
                })
            })
        })

    </script>
{% endblock %}